language: java
sudo: true
jdk:
  - oraclejdk7
install: true
script: "./gradle/buildViaTravis.sh"
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
- test $TRAVIS_PULL_REQUEST = false && openssl aes-256-cbc -K $encrypted_b1ee0fc237d8_key -iv $encrypted_b1ee0fc237d8_iv
  -in gradle.properties.enc -out gradle.properties -d || true
after_success:
- "./gradlew jacocoTestReport coveralls"
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2789fa0cc6521142fbb2
    on_success: change
    on_failure: always
    on_start: never
